### ISSUE TITLE
MAUI port?

### ISSUE THREAD

**Issue by mfeingol** [dotMorten/MauiEx#97]
Not sure if you're still maintaining this, @dotMorten, but it would be nice to have a .NET MAUI port of this control. I don't think there's an equivalent one in the box with a floating listview. Thanks!

**Comment by Welchen** [comment]
I was wondering as well if there is a MAUI version in the works.

**Comment by davefxy** [comment]
I guess you havent had a dull moment. Your AutoSuggestBox implementation has no equivalent yet in Maui. I thought I might be able to use the Maui SearchBox implmentation but it needs to be used in a toolbar. If you were to consider the Android version, that would be fantastic.

**Comment by davefxy** [comment]
I have managed to port your AutoSuggestBox  as a Net Maui handler. I have a working Android version. Everything is in place for iOS. The iOS version needs some work on the iOS unique code in AutoSuggestBox handler. You can let me know where to make the Maui version of the AutoSuggestBox control project available.

**Comment by davefxy** [comment]
I have successfully migrated your AutoSuggestBox control project as a Net Maui style handler Net 7 implementation. I have a working Android version and iOS version. It is at :  https://github.com/davefxy/dotMorten.Maui.AutoSuggestBox

**Comment by dotMorten** [comment]
@mfeingol @davefxy Alright all done! It's [up on nuget.org](https://www.nuget.org/packages/dotMorten.MauiEx/1.0.0-preview1) now

**Comment by mfeingol** [comment]
Thank you! Seems to be working well on Android.
